# iw配置
iw:
  redis:
    host: ${IW_REDIS_HOST:127.0.0.1}
    port: ${IW_REDIS_PORT:6379}
    database: ${IW_REDIS_DATABASE:0}
    username: ${IW_REDIS_USERNAME:}
    password: ${IW_REDIS_PASSWORD:}
  db:
    driver-class: ${IW_DB_DRIVER_CLASS:}
    url: ${IW_DB_URL:}
    username: ${IW_DB_USERNAME:}
    password: ${IW_DB_PASSWORD:}
  feign:
    secret: ${IW_INTERNAL_SECRET:dev-secret}
  dao:
    dataPermission:
      enabled: true
      enable-table-names:
        - bookkeeping_records
        - bookkeeping_actions
        - bookkeeping_budget
        - bookkeeping_wallet
        - bookkeeping_wallet_records
        - bookkeeping_membership_subscription
        - points_total
        - points_records
        - points_task_basics
        - points_task_group
        - points_task_plan
        - points_task_fixed
        - eat_meal
        - eat_fridge_food
      share-scope-enable-table-names:
        - bookkeeping_records

# 服务器配置
server:
  port: 18004

# spring 配置
spring:
  application:
    name: iw-bookkeeping-service
  profiles:
    default: dev
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# springdoc 配置
springdoc:
  swagger-ui:
    path: /doc.html
  packages-to-scan:
    - com.itwray.iw.bookkeeping.controller
