create table ai_image_generate_record
(
    id                       int unsigned auto_increment             not null comment 'id',
    dedupe_key               char(64)                                not null comment '去重key',
    business_type            varchar(64)   default ''                not null comment '业务类型枚举',
    business_custom_category varchar(128)  default ''                not null comment '业务自定义分类',
    business_category        varchar(255)  default ''                not null comment '业务分类',
    business_id              varchar(64)   default ''                not null comment '业务id',
    source_image_url         varchar(512)  default ''                not null comment '源图片地址',
    prompt                   text                                   null comment '生成提示词',
    task_id                  varchar(64)   default ''                not null comment '业务任务id',
    external_task_id         varchar(128)  default ''                not null comment 'AI供应商任务id',
    status                   varchar(32)   default 'processing'      not null comment '状态(processing/success/failed)',
    result_image_url         varchar(512)  default ''                not null comment '生成图片地址',
    result_mime_type         varchar(64)   default ''                not null comment '生成图片MIME类型',
    revised_prompt           varchar(1024) default ''                not null comment '供应商优化后的提示词',
    error_message            varchar(512)  default ''                not null comment '错误信息',
    hit_count                int unsigned  default 1                 not null comment '命中次数',
    last_hit_time            datetime                                null comment '最近命中时间',
    deleted                  tinyint(1)    default 0                 not null comment '是否删除',
    create_time              datetime      default CURRENT_TIMESTAMP not null comment '创建时间',
    update_time              datetime      default CURRENT_TIMESTAMP not null comment '更新时间',
    user_id                  int unsigned  default 0                 not null comment '用户id',
    primary key (id),
    unique key uk_dedupe_key (dedupe_key),
    key idx_business (business_type, business_id),
    key idx_status (status),
    key idx_user_id (user_id)
) comment 'AI图片生成记录表';
