create table wardrobe_item
(
    id             int unsigned auto_increment             not null comment 'id',
    item_name      varchar(64)   default ''                not null comment '衣物名称',
    item_image     varchar(255)  default ''                not null comment '衣物图片',
    category       tinyint       default 0                 not null comment '衣物品类(1上装 2下装 3连衣裙 4内衣 5袜子 6鞋履 7配饰 8帽子 9包袋 10首饰 11其他)',
    item_style     smallint unsigned default 0             not null comment '衣物款式',
    color_name     varchar(32)   default ''                not null comment '颜色名称',
    color_hex      varchar(16)   default ''                not null comment '颜色hex',
    season_tags    varchar(64)   default ''                not null comment '季节标签',
    scene_tags     varchar(128)  default ''                not null comment '场景标签',
    style_tags     varchar(128)  default ''                not null comment '风格标签',
    brand          varchar(64)   default ''                not null comment '品牌',
    size           varchar(32)   default ''                not null comment '尺码',
    material       varchar(64)   default ''                not null comment '材质',
    purchase_channel varchar(64) default ''                not null comment '购买渠道',
    storage_location varchar(64) default ''                not null comment '存放位置',
    purchase_date  date                                   null comment '购买日期',
    price          decimal(10,2) default 0                 not null comment '价格',
    custom_tags    varchar(255)  default ''                not null comment '自定义标签',
    status         tinyint       default 1                 not null comment '状态(1在穿 2闲置 5已淘汰)',
    wear_count     int unsigned  default 0                 not null comment '穿着次数',
    last_wear_date date                                   null comment '最近穿着日期',
    remark         varchar(255)  default ''                not null comment '备注',
    deleted        tinyint(1)    default 0                 not null comment '是否删除',
    create_time    datetime      default CURRENT_TIMESTAMP not null comment '创建时间',
    update_time    datetime      default CURRENT_TIMESTAMP not null comment '更新时间',
    user_id        int unsigned  default 0                 not null comment '用户id',
    primary key (id),
    key idx_user_status (user_id, status),
    key idx_category (category),
    key idx_item_style (item_style),
    key idx_last_wear_date (last_wear_date)
) comment '衣柜衣物表';

create table wardrobe_outfit
(
    id             int unsigned auto_increment             not null comment 'id',
    outfit_name    varchar(64)   default ''                not null comment '搭配名称',
    cover_image    varchar(255)  default ''                not null comment '搭配封面',
    season_tags    varchar(64)   default ''                not null comment '季节标签',
    scene_tags     varchar(128)  default ''                not null comment '场景标签',
    style_tags     varchar(128)  default ''                not null comment '风格标签',
    custom_tags    varchar(255)  default ''                not null comment '自定义标签',
    color_summary  varchar(128)  default ''                not null comment '颜色摘要',
    item_count     tinyint       default 0                 not null comment '衣物数量',
    wear_count     int unsigned  default 0                 not null comment '穿着次数',
    last_wear_date date                                   null comment '最近穿着日期',
    status         tinyint       default 1                 not null comment '状态(1正常 2归档)',
    remark         varchar(255)  default ''                not null comment '备注',
    deleted        tinyint(1)    default 0                 not null comment '是否删除',
    create_time    datetime      default CURRENT_TIMESTAMP not null comment '创建时间',
    update_time    datetime      default CURRENT_TIMESTAMP not null comment '更新时间',
    user_id        int unsigned  default 0                 not null comment '用户id',
    primary key (id),
    key idx_user_status (user_id, status),
    key idx_last_wear_date (last_wear_date)
) comment '衣柜搭配表';

create table wardrobe_outfit_item
(
    id          int unsigned auto_increment             not null comment 'id',
    outfit_id   int unsigned                            not null comment '搭配id',
    item_id     int unsigned                            not null comment '衣物id',
    item_name   varchar(64)   default ''                not null comment '衣物名称快照',
    item_image  varchar(255)  default ''                not null comment '衣物图片快照',
    category    tinyint       default 0                 not null comment '衣物品类快照',
    item_style  smallint unsigned default 0             not null comment '衣物款式快照',
    sort        tinyint       default 0                 not null comment '排序',
    deleted     tinyint(1)    default 0                 not null comment '是否删除',
    create_time datetime      default CURRENT_TIMESTAMP not null comment '创建时间',
    update_time datetime      default CURRENT_TIMESTAMP not null comment '更新时间',
    user_id     int unsigned  default 0                 not null comment '用户id',
    primary key (id),
    key idx_outfit_id (outfit_id),
    key idx_item_id (item_id),
    key idx_user_id (user_id)
) comment '衣柜搭配衣物表';

create table wardrobe_wear_record
(
    id           int unsigned auto_increment             not null comment 'id',
    wear_date    date                                    not null comment '穿着日期',
    outfit_id    int unsigned  default 0                 not null comment '搭配id',
    outfit_name  varchar(64)   default ''                not null comment '搭配名称快照',
    scene_tags   varchar(128)  default ''                not null comment '场景标签',
    weather_text varchar(64)   default ''                not null comment '天气',
    mood_text    varchar(64)   default ''                not null comment '心情',
    record_type  tinyint       default 2                 not null comment '记录类型(1计划 2已穿)',
    item_count   tinyint       default 0                 not null comment '衣物数量',
    remark       varchar(255)  default ''                not null comment '备注',
    deleted      tinyint(1)    default 0                 not null comment '是否删除',
    create_time  datetime      default CURRENT_TIMESTAMP not null comment '创建时间',
    update_time  datetime      default CURRENT_TIMESTAMP not null comment '更新时间',
    user_id      int unsigned  default 0                 not null comment '用户id',
    primary key (id),
    key idx_wear_date (wear_date),
    key idx_outfit_id (outfit_id),
    key idx_user_id (user_id)
) comment '衣柜穿着记录表';

create table wardrobe_wear_record_item
(
    id          int unsigned auto_increment             not null comment 'id',
    record_id   int unsigned                            not null comment '穿着记录id',
    item_id     int unsigned                            not null comment '衣物id',
    item_name   varchar(64)   default ''                not null comment '衣物名称快照',
    item_image  varchar(255)  default ''                not null comment '衣物图片快照',
    category    tinyint       default 0                 not null comment '衣物品类快照',
    item_style  smallint unsigned default 0             not null comment '衣物款式快照',
    sort        tinyint       default 0                 not null comment '排序',
    deleted     tinyint(1)    default 0                 not null comment '是否删除',
    create_time datetime      default CURRENT_TIMESTAMP not null comment '创建时间',
    update_time datetime      default CURRENT_TIMESTAMP not null comment '更新时间',
    user_id     int unsigned  default 0                 not null comment '用户id',
    primary key (id),
    key idx_record_id (record_id),
    key idx_item_id (item_id),
    key idx_user_id (user_id)
) comment '衣柜穿着记录衣物表';

create table wardrobe_image_optimization_task
(
    id                  int unsigned auto_increment              not null comment 'id',
    task_id             varchar(64)                              not null comment '业务任务id',
    item_id             int unsigned                             not null comment '衣物id',
    fingerprint         char(64)                                 not null comment '任务指纹',
    source_image_url    varchar(512) default ''                  not null comment '不可变源图URL',
    user_prompt         varchar(1024) default ''                 not null comment '用户补充要求',
    normalized_prompt   text                                     null comment '服务端归一化提示词',
    rule_version        varchar(64) default ''                   not null comment '优化规则版本',
    input_snapshot      text                                     null comment '输入元数据快照JSON',
    status              varchar(32) default 'queued'             not null comment 'queued/running/succeeded/failed/cancelled',
    current_attempt_no  int unsigned default 1                   not null comment '当前attempt号',
    result_image_url    varchar(512) default ''                  not null comment '当前生成结果URL',
    error_message       varchar(512) default ''                  not null comment '错误信息',
    result_deleted_time datetime                                 null comment '结果被用户删除时间',
    complete_time       datetime                                 null comment '完成时间',
    active_item_key     varchar(64) generated always as
        (case when deleted = 0 and status in ('queued', 'running') then concat(user_id, ':', item_id) else null end) stored,
    deleted             tinyint(1) default 0                     not null comment '是否删除',
    create_time         datetime default CURRENT_TIMESTAMP       not null comment '创建时间',
    update_time         datetime default CURRENT_TIMESTAMP       not null comment '更新时间',
    user_id             int unsigned default 0                   not null comment '用户id',
    primary key (id),
    unique key uk_task_id (task_id),
    unique key uk_user_item_fingerprint (user_id, item_id, fingerprint),
    unique key uk_active_item (active_item_key),
    key idx_user_item (user_id, item_id),
    key idx_status (status),
    key idx_user_id (user_id)
) comment '衣柜图片优化任务表';

create table wardrobe_image_optimization_attempt
(
    id                int unsigned auto_increment        not null comment 'id',
    task_id           varchar(64)                        not null comment '业务任务id',
    attempt_no        int unsigned default 1             not null comment 'attempt号',
    status            varchar(32) default 'queued'       not null comment 'queued/running/succeeded/failed/cancelled',
    claim_token       varchar(64) default ''             not null comment '执行认领令牌',
    claim_expire_time datetime                           null comment '认领租约到期时间',
    next_poll_time    datetime                           null comment '下次外部任务轮询时间',
    start_time        datetime                           null comment '开始时间',
    deadline_time     datetime                           null comment '截止时间',
    provider          varchar(64) default ''             not null comment '外部能力提供方',
    external_task_id  varchar(128) default ''            not null comment '外部任务id',
    result_image_url  varchar(512) default ''            not null comment '上传后的结果URL',
    result_mime_type  varchar(64) default ''             not null comment '结果MIME类型',
    revised_prompt    varchar(1024) default ''           not null comment '供应商修订提示词',
    error_message     varchar(512) default ''            not null comment '错误信息',
    complete_time     datetime                           null comment '完成时间',
    deleted           tinyint(1) default 0               not null comment '是否删除',
    create_time       datetime default CURRENT_TIMESTAMP not null comment '创建时间',
    update_time       datetime default CURRENT_TIMESTAMP not null comment '更新时间',
    user_id           int unsigned default 0             not null comment '用户id',
    primary key (id),
    unique key uk_task_attempt (task_id, attempt_no),
    key idx_runnable (status, next_poll_time, claim_expire_time),
    key idx_deadline (status, deadline_time),
    key idx_user_id (user_id)
) comment '衣柜图片优化执行attempt表';

create table wardrobe_image_file_cleanup
(
    id                   int unsigned auto_increment        not null comment 'id',
    task_id              varchar(64) default ''             not null comment '关联业务任务id',
    item_id              int unsigned                       null comment '关联衣物id',
    attempt_no           int unsigned                       null comment '关联attempt号',
    file_url             varchar(512)                       not null comment '待删除OSS文件URL',
    reason               varchar(64) default ''             not null comment '清理原因',
    status               varchar(32) default 'pending'      not null comment 'pending/retrying/succeeded/manual_required',
    retry_count          int unsigned default 0             not null comment '失败次数',
    next_retry_time      datetime                           not null comment '下次重试时间',
    last_attempt_time    datetime                           null comment '最后尝试时间',
    last_error           varchar(512) default ''            not null comment '最后错误',
    claim_token          varchar(64) default ''             not null comment '清理认领令牌',
    claim_expire_time    datetime                           null comment '认领租约到期时间',
    manual_required_time datetime                           null comment '转人工时间',
    complete_time        datetime                           null comment '完成时间',
    deleted              tinyint(1) default 0               not null comment '是否删除',
    create_time          datetime default CURRENT_TIMESTAMP not null comment '创建时间',
    update_time          datetime default CURRENT_TIMESTAMP not null comment '更新时间',
    user_id              int unsigned default 0             not null comment '用户id',
    primary key (id),
    unique key uk_file_url (file_url),
    key idx_runnable (status, next_retry_time, claim_expire_time),
    key idx_user_id (user_id)
) comment '衣柜图片OSS清理任务表';
